- examples/list_disk_snapshots.py
When a VM is created from template with Thin Storage Allocation,
the parent of one of the snapshots will be the template image, thus
not returned in the result set for the list disksnapshots request.
In this case, when requesting snapshots of a disk created this way -
this script returns an error.
To handle this, the patch:
- Calls for snapshots list with the include_template flag
- After the main loop detects snapshots with disk.id == args.disk_id
another loop goes through the remaining snapshots, looking for ones
that are parents of the already found snapshots, thus completing
the snapshot chain.
Bug-Url: https://bugzilla.redhat.com/1900597
> list_disk_snapshots.py: look for template snapshots in the chain

- automation/build-artifacts.sh
- build.sh
From now we are using pypi version of the sdk, python38 is no longer needed.
> Automation: disable python38 build

- examples/backup_vm.py
In commit a4a0339f49cdc2bb3c6163f1d79579888f414fdd
Add backup UUID for backup vm (#28)
the argument was added as --backup_uuid to "start" "full" and
"incremental" sub commands. This is not consistent with --backup-uuid
argument of the "download" sub command and other arguments (--disk-uuid,
--backup-dir).
Staring backup with --backup--uuid argument fails with:
$ ./backup_vm.py -c engine-dev start --backup-uuid 1-2-3-4
usage: backup_vm.py [-h] -c CONFIG [--debug] [--logfile LOGFILE]
{full,incremental,start,download,stop} ...
backup_vm.py: error: unrecognized arguments: --backup-uuid
> backup_vm: Fix --backup-uuid argument

- examples/upload_disk.py
Add --inactivity-timeout command line option. I don't think that any
user will need this, but it very useful for testing that engine pass the
right value to ovirt-imageio.
For more info on why inactivity timeout is needed see:
https://github.com/oVirt/ovirt-imageio/issues/14
> upload_disk: Show how to set inactivity timeout

- .github/workflows/build.yaml
Fix issue where environment variable with the generated
documentation directory was not propagated to publish-doc job.
> Fix issue when pushing generated documentation

- .github/workflows/build.yaml
Use upload/download artifacts instead of a cache to share generated
documentation between jobs.
> Use artifacts instead of cache to share generated doc 

- .github/workflows/build.yaml
Removes renaming generated files as they are already correctly named
> No longer need to rename generated files

- .github/workflows/build.yaml
Don't use single quotes for documentation target folder value.
> Fix documentation target folder value

- .github/workflows/build.yaml
issue was that we use a custom pdoc template https://github.com/oVirt/ovirt-engine-sdk/blob/gh-pages/module.html.jinja2
When the docs were being created it was missing the template.
(Can't remove the https://github.com/oVirt/python-ovirt-engine-sdk4/blob/main/.github/workflows/build.yaml#L138-L144 because it is in another github "task" and it did not share .git folder from the previous task so we need to refresh the .git folder)
> automation: fix docs paths

- .github/workflows/build.yaml
We can't use the GITHUB_TOKEN because it is limited by permissions.
> automation: change secrets to deploy key

- examples/backup_vm.py
Previously a really not user-friendly error was raised when there were no disks to backup:
i.e., when backup was initiated on a VM without any disks attached.
Both backup script output & engine errors looked like an internal unexpected error rather
then displaying an error message that should help the user to understand what is wrong.
Adding a simple validation and short error message to improve the user experience.
Signed-off-by: Pavel Bar <pbar@redhat.com>
> Add checks for non-empty disks when running a backup

- examples/backup_vm.py
Various improvements to make it more useful for testing backup.
The most important change is creating a qcow2 chain when downloading
backups. This avoid the need to rebase backup files, which is pretty
hard to do. This makes it very easy to create several incremental
backups and restore any of the backups directly to storage.
To make this possible, we include now the checkpoint id in the
backup file name. This allows finding the previous backup for
the specified checkpoint id.
There are also some minor improvements to logging, backup file names,
and error handling.
> Improve backup vm script

- examples/checkpoints.py
Add new command to list checkpoints. Similar to the purge command, it
can list checkpoints older than specified days.
This command is useful for managing checkpoints, and an example how to
find checkpoints and use checkpoint properties.
> checkpoints: Add list command

- .automation/build-srpm.sh
The https://github.com/oVirt/python-ovirt-engine-sdk4/pull/67 was changed only in build.sh, to regenerate the rpms we need to also change the build-srpm.sh
> Fix 4.5.1 release packages

- examples/delete_disks.py
This example deletes disks from a storage domain based on their description.
The default description matches the description added by the
add_disks.py example, so this example can be used to clean up after
running add_disks.py.
The script shows how to delete a massive number of disks,
by submitting many remove disk requests one after the other.
> Add delete_disks.py example

- examples/add_floating_disk.py
- examples/add_nfs_iso_storage_domain.py
- examples/add_vm_disk.py
- examples/add_vm_from_template_version.py
- examples/asynchronous_inventory.py
- examples/attach_nfs_data_storage_domain.py
- examples/attach_nfs_iso_storage_domain.py
- examples/checksum_disk.py
- examples/data_center_maintenance.py
- examples/deactivate_disk_attachment.py
- examples/download_disk.py
- examples/download_disk_snapshot.py
- examples/extend_disk.py
- examples/image_transfer.py
- examples/import_glance_image.py
- examples/import_vm.py
- examples/list_disk_snapshots.py
- examples/list_glance_images.py
- examples/list_vm_snapshots.py
- examples/set_vm_lease_storage_domain.py
- examples/sparsify_disk.py
- examples/upload_disk.py
Switched some storage examples (using disks_service, storage_domains_service and image_transfers_service) to explicitly use python3 and fixed the resulting incompatibilities.
All examples are supposed to use python3 in the end.
Signed-off-by: Rob Linden <rlinden@redhat.com>
> Switched some storage examples (using disks_service) to explicitly use python3 and fixed the resulting incompatibilities.

- python-ovirt-engine-sdk4.spec.in
Switch from Python 3.8 to 3.9 on EL8 to be able to support
ansible-core-2.13
> Switch from Python 3.8 to 3.9 on EL8

- .github/workflows/build.yaml
- Alway use latest version if ovirt gh actions
> use latest ovirt actions

- python-ovirt-engine-sdk4.spec.in
The ansible-core 2.14 uses python3.11 on Centos 9 stream instead of the default system python3.9.
We need to build the rpm to use the SDK with the ansible-core 2.14, which forces the python library to python3.11 so the ansible can use the SDK.
> Add Python 3.11 subpackage to be usable in ansible-core 2.14

- .github/workflows/build.yaml
Issue:
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.68.0-1ubuntu2.15_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
```
Fix: update the system repos before installing
> Fix ci libcurl4-openssl 404 status

- .github/workflows/build.yaml
- lib/ovirtsdk4/__init__.py
- lib/ovirtsdk4/readers.py
- lib/ovirtsdk4/service.py
- lib/ovirtsdk4/services.py
- lib/ovirtsdk4/types.py
- lib/ovirtsdk4/writer.py
- lib/ovirtsdk4/writers.py
- pdoc/custom.css
Documentation updated so that it builds properly with most recent pdoc version.
Alterations made:
- Links now work
- codeblocks updated
- full documentation now renders
Built version of the documentation that would be merged:
https://jasperb-teamblue.github.io/python-ovirt-engine-sdk4/ate/ovirtsdk4.html
Solves issue: https://github.com/oVirt/python-ovirt-engine-sdk4/issues/55
> ci: updated build to work with most recent pdoc version

- python-ovirt-engine-sdk4.spec.in
Since we don't support el8 anymore and rhel9.3+ has ansible-core on it's default python version again (see [1]), we can just drop the additional python3.11/python3.12 packages.
[1]: https://www.redhat.com/en/blog/updates-using-ansible-core-in-rhel
> spec: drop python3.11 and python3.12 packages
