build.sh, python-ovirt-engine-sdk4.spec.in
=> Release 4.4.15

automation/build-artifacts.packages.el9stream, automation/build-artifacts.sh, automation/check-merged.packages.el9stream, automation/check-patch.packages.el9stream
=> Fix el9stream automation

examples/recreate_vm.py
Added example that shows how to recreate VM while maintaining VM permissions
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2012776
=> Added example to recreate VM

.copr/Makefile, README.adoc
Enable COPR builds.
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
=> copr: enable copr builds

examples/reprovision_stateless_vm_in_pool.py
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2012776
=> update recreate_vm script name and title

.gitignore, PKG-INFO.in, build.sh, lib/ovirt_engine_sdk_python.egg-info/PKG-INFO.in, lib/ovirtsdk4/version.py.in, setup.py.in
Automation: replace @RPM_VERSION@ in version.py with build version
=> Automation: add wrapper around build version

examples/backup_vm.py
Add the --skip-download argument in a new helper for adding testing
related arguments.
=> backup_vm: Remove duplicate --skip-download

examples/checkpoints.py
Address comments from #34
- Various text fixes
- Add timeout for removing a checkpoint
=> Improve checkpoints example script

.github/workflows/build.yaml
=> Debug issue during publishing documentation

.github/workflows/build.yaml
- Fix documentation target folder value
- Fix issue publishing generated documention
=> fix copying gen doc

.github/workflows/build.yaml
=> Revert 42a7601f3954c74006e3326e1aa0a04da5fdf31f

.github/workflows/build.yaml
The push of the doc failed, when I have tested it on my fork it worked hopefully this will resolve in this repository.
=> Add GitHub token to automation

.github/workflows/build.yaml
Add GITHUB_TOKEN write permissions to repository.
=> Add permissions to GITHUB_TOKEN

build.sh, python-ovirt-engine-sdk4.spec.in
=> release version 4.5.1

.automation/build-srpm.sh, python-ovirt-engine-sdk4.spec.in
=> Release version 4.5.2

.automation/build-srpm.sh
=> Post release version 4.5.2

.automation/build-rpm.sh
Automation: upload tarball to artifacts
=> Automation: upload tarball to artifacts

.automation/build-rpm.sh, .automation/build-srpm.sh, .automation/generate-setup-files.sh, .copr/Makefile, .github/workflows/build.yaml
This patch adds the new workflow generate-documentation
=> Add Documentation Workflow

.automation/generate-setup-files.sh
=> change to version 4.6.0 snapshot

README.adoc
=> trigger 4.5 doc publish

README.adoc
=> trigger 4.5 doc publish (#85)

README.adoc
=> trigger 4.5 doc publish (#85) (#86)

.github/workflows/build.yaml
=> specify sdk_4.5 branch in build.yml

.automation/build-rpm.sh, .automation/build-srpm.sh, .copr/Makefile
- Simplify execution of generate-setup-files.sh
- Fix tarball generation issue
=> fix tarball generation issues main

index.html, index.html.md
=> add 4.5 branch to index.html

.github/workflows/build.yaml
=> Use oVirt specific actions in the build workflow

.automation/generate-setup-files.sh, python-ovirt-engine-sdk4.spec.in
=> Release 4.6.0

.automation/generate-setup-files.sh
=> Post release 4.6.0

.automation/generate-setup-files.sh, python-ovirt-engine-sdk4.spec.in
Add Python 3.11 subpackage to be usable in ansible-core 2.14 for el8
=> Release 4.6.2-1
